"""Initial migration.

Revision ID: 12b83a999f15
Revises: 
Create Date: 2022-06-22 12:22:16.190450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12b83a999f15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['cnumber'])
    op.add_column('students', sa.Column('enrolled_courses', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'enrolled_courses')
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
